version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    volumes:
      - .:/home/dev-user/app:z
      # - ./.docker/zsh/powerlevel10k/.p10k.zsh:~/.p10k.zsh:delegated
      - ./.devcontainer/zsh_history:/home/dev-user/.zsh_history:delegated
